name: CI

on: [push, pull_request]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - run: dotnet test dfalex.sln
