name: CI

on: [push, pull_request]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-18.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Run GitVersion
        uses: docker://gittools/gitversion:5.1.4-linux
        with:
          args: -output buildserver -nocache

      - run: env

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Disable .Net Welcome
        run: touch "$HOME/.dotnet/$(dotnet --version).dotnetFirstUseSentinel"

      - name: Build
        run: dotnet build --configuration Release dfalex.sln

      - name: Test
        run: dotnet test --configuration Release --no-build dfalex.sln
